# Generated by Django 4.0.5 on 2022-06-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('release_date', models.DateField()),
                ('director_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
