# Generated by Django 4.0.5 on 2022-06-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
