# Generated by Django 4.0.5 on 2022-06-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
